### ISSUE TITLE
Permission denied error on Travis CI.

### ISSUE THREAD

**Issue by k-kinzal** [elct9620/heroku-buildpacks-php-with-phalcon#2]
I deploy to heroku with Travis CI. but error happend.

> Deploying application
> Checking for app files to sync... done, 20 files needed
> ]0;Uploading: 100.0% (ETA: 0s)]0;
> Launching build process... done 
> Preparing app for compilation... done 
> Fetching buildpack... done 
> Detecting buildpack... bin/compile: line 97: /tmp/buildpack_D5Eud/bin/detect: Permission denied
> failed

.travis.yml

``` yml
deploy:
  provider: heroku
  buildpack: https://github.com/elct9620/heroku-buildpacks-php-with-phalcon.git
```

Please grant executable permission to file.
